name: native_splash_screen
description: A new Flutter project.
 
publish_to: 'none'   
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0" 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0 

# package 
  flutter_native_splash: ^2.0.4
flutter_native_splash:
  color: "#f5cb42"
  image: assets/grey.png
  
# flutter clean
# flutter pub get
# flutter pub run flutter_native_splash:create  



flutter: 
  uses-material-design: true
  assets:
    - assets/ 
